# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-05 10:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likethis',
            options={'ordering': ('-created',), 'verbose_name': 'like this', 'verbose_name_plural': 'likes this'},
        ),
    ]
