# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-27 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0002_auto_20190127_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='ideas', to='myapp1.Category', verbose_name='Categories'),
        ),
    ]
