# myapp1/migrations/004_copy_categories.py
# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-27 04:45
from __future__ import unicode_literals

from django.db import models, migrations


def copy_categories(apps, schema_editor):
    Idea = apps.get_model("myapp1", "Idea")
    for idea in Idea.objects.all():
        if idea.category:
            idea.categories.add(idea.category)


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0003_categories_added'),
    ]

    operations = [
        migrations.RunPython(copy_categories),
    ]
