# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-31 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0005_remove_idea_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Idea Category', 'verbose_name_plural': 'Idea Categories'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='title',
        ),
        migrations.AddField(
            model_name='category',
            name='title_sw',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title (sw)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='is_original',
            field=models.BooleanField(default=False, verbose_name='Original'),
        ),
        migrations.AddField(
            model_name='idea',
            name='subtitle_sw',
            field=models.CharField(blank=True, max_length=200, verbose_name='Subtitle (sw)'),
        ),
    ]
