# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-01 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0006_changes_in_myapp1_and_quotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title_de',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title (de)'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.CharField(default='Art', max_length=200, verbose_name='Title (en)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='title_fr',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title (fr)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_de',
            field=models.TextField(blank=True, verbose_name='Description (de)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Description (en)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='description_fr',
            field=models.TextField(blank=True, verbose_name='Description (fr)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='subtitle_de',
            field=models.CharField(blank=True, max_length=200, verbose_name='Subtitle (de)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Subtitle (en)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='subtitle_fr',
            field=models.CharField(blank=True, max_length=200, verbose_name='Subtitle (fr)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_de',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title (de)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_en',
            field=models.CharField(default='Art', max_length=200, verbose_name='Title (en)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='idea',
            name='title_fr',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title (fr)'),
        ),
    ]
