# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-16 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0007_adding_title_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
