# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-16 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0008_manually_added_id_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
