# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-19 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import locations.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(help_text='A short label, generally used in URLs.')),
                ('small_image', models.ImageField(blank=True, null=True, upload_to=locations.models.upload_to, verbose_name='Small Image')),
                ('medium_image', models.ImageField(blank=True, null=True, upload_to=locations.models.upload_to, verbose_name='Medium Image')),
                ('large_image', models.ImageField(blank=True, null=True, upload_to=locations.models.upload_to, verbose_name='Large Image')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
    ]
