# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-06 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, max_length=255, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.CharField(blank=True, choices=[('UG', 'Uganda'), ('KE', 'Kenya'), ('RW', 'Rwanda'), ('TZ', 'Tanzania')], max_length=2, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='location',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='postal code'),
        ),
        migrations.AddField(
            model_name='location',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='street_address'),
        ),
        migrations.AddField(
            model_name='location',
            name='village',
            field=models.CharField(blank=True, max_length=255, verbose_name='village'),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude (Lat.) is the angle between any point and the equator (north pole is at 90; south pole is at -90).', null=True, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude (Long.) is the angle east or west of an arbitrary point on Earth from Greenwich (UK), which is the international zero-longitude point (longitude=0 degrees). The anti-meridian of Greenwich is both 180 (direction to east) and -180 (direction to west).', null=True, verbose_name='longitude'),
        ),
    ]
