# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-25 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.IntegerField(default=2000, verbose_name='Year Released'),
        ),
    ]
